/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Design;

import com.sisary.global.Global;
import com.sisary.thread.Serpiente;
import com.sisary.thread.Snack;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import javax.swing.JPanel;
import javax.swing.border.LineBorder;

/**
 *
 * @author Luis Fernando
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    private int point_X;
    private int point_Y;

    public Interfaz() {
        initComponents();
        this.setExtendedState(Interfaz.MAXIMIZED_BOTH);
        this.setResizable(false);
        PaintPoints();
        CreateBotana();
        addMouseMotionListenerToGamePanel();
        addMouseListenerToInterfaz();
        InitSnake();
        Global.LabelScore = this.scoreLabel;
        Global.LabelVelocidad = this.velocidadLabel;
        Global.LabelFaults = this.faultsLabel;
        Global.playSound("/audio/principal.wav", true);
    }

    private void InitSnake() {
        Serpiente snake = new Serpiente();
        snake.start();
    }

    private void CreateBotana() {
        Snack snack = new Snack();
        snack.start();
    }

    private void addMouseMotionListenerToGamePanel() {
        GamePanel.addMouseMotionListener(new MouseMotionAdapter() {
            @Override
            public void mouseMoved(MouseEvent e) {
                int mouseX = e.getX();
                int mouseY = e.getY();

                for (JPanel panel : Global.gridList) {
                    if (panel.getBounds().contains(mouseX, mouseY)) {
                        point_X = panel.getX();
                        point_Y = panel.getY();

                        int sizeWidth = GamePanel.getWidth() / 30;
                        int sizeHeight = GamePanel.getHeight() / 18;

                        int col = point_X / sizeWidth;
                        int row = point_Y / sizeHeight;

                        Global.nextIndex = row * 30 + col;
                        break;
                    }
                }
            }
        });
    }

    private void addMouseListenerToInterfaz() {
        Fondo.addMouseMotionListener(new MouseMotionAdapter() {
            @Override
            public void mouseMoved(MouseEvent e) {
                int mouseX = e.getX();
                int mouseY = e.getY();

                Global.puntoX = mouseX;
                Global.puntoY = mouseY;
                Global.nextIndex = -1;

                if (Global.puntoX >= 0 && Global.puntoX <= 248) {
                    Global.banderaLeft = true;
                    Global.banderaRight = false;                    
                    Global.banderaUp = false;
                    Global.banderaDown = false;

                } else if (Global.puntoX >= 1287 && Global.puntoX <= 1533) {
                    Global.banderaLeft = false;
                    Global.banderaRight = true;                    
                    Global.banderaUp = false;
                    Global.banderaDown = false;
                    
                } else if (Global.puntoY >= 0 && Global.puntoY <= 170) {
                    Global.banderaLeft = false;
                    Global.banderaRight = false;                    
                    Global.banderaUp = true;
                    Global.banderaDown = false;
                } else if (Global.puntoY >= 792 && Global.puntoY <= 838) {
                    Global.banderaLeft = false;
                    Global.banderaRight = false;                    
                    Global.banderaUp = false;
                    Global.banderaDown = true;
                }
            }
        });
    }

    private void PaintPoints() {
        int width = 1050 ;
        int height = 630;
        this.GamePanel.setLayout(null);
        for (int i = 0; i < 18; i++) {
            for (int j = 0; j < 30; j++) {
                JPanel punto = new JPanel();

                int sizeWidth = width / 30;
                int sizeHeight = height / 18;

                int puntoX = j * sizeWidth;
                int puntoY = i * sizeHeight;

                punto.setBounds(puntoX, puntoY, sizeWidth, sizeHeight);
                punto.setBackground(new Color(102, 102, 102));
                punto.setBorder(new LineBorder(new Color(101, 101, 101), 1));
                Global.gridList.add(punto);
                this.GamePanel.add(punto);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        GamePanel = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jPanel1 = new javax.swing.JPanel();
        velocidadLabel = new javax.swing.JLabel();
        scoreLabel = new javax.swing.JLabel();
        faultsLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Fondo.setBackground(new java.awt.Color(51, 51, 51));

        GamePanel.setBackground(new java.awt.Color(102, 102, 102));
        GamePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout GamePanelLayout = new javax.swing.GroupLayout(GamePanel);
        GamePanel.setLayout(GamePanelLayout);
        GamePanelLayout.setHorizontalGroup(
            GamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        GamePanelLayout.setVerticalGroup(
            GamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 268, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(43, 121, 108));

        velocidadLabel.setFont(new java.awt.Font("Ubuntu Medium", 0, 18)); // NOI18N
        velocidadLabel.setForeground(new java.awt.Color(255, 255, 255));
        velocidadLabel.setText("Velocidad: 100");

        scoreLabel.setFont(new java.awt.Font("Ubuntu Medium", 0, 18)); // NOI18N
        scoreLabel.setForeground(new java.awt.Color(255, 255, 255));
        scoreLabel.setText("Score: 0 ");

        faultsLabel.setFont(new java.awt.Font("Ubuntu Medium", 0, 18)); // NOI18N
        faultsLabel.setForeground(new java.awt.Color(255, 255, 255));
        faultsLabel.setText("Faults 0 ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(velocidadLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(scoreLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(faultsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(106, 106, 106))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(velocidadLabel)
                    .addComponent(scoreLabel)
                    .addComponent(faultsLabel))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout FondoLayout = new javax.swing.GroupLayout(Fondo);
        Fondo.setLayout(FondoLayout);
        FondoLayout.setHorizontalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(324, 324, 324))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoLayout.createSequentialGroup()
                        .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(GamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(236, 236, 236))))
        );
        FondoLayout.setVerticalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(GamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(80, 80, 80))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Fondo;
    private javax.swing.JPanel GamePanel;
    private javax.swing.JLabel faultsLabel;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel scoreLabel;
    private javax.swing.JLabel velocidadLabel;
    // End of variables declaration//GEN-END:variables
}
